site_name: 'asdasd'
docs_dir: '../../docs/en'                           # Where to find the English markdown files
site_dir: '../../generated/en'                      # Where to put the English HTML files

theme:
  name: material
  language: en
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Português
      link: /pt/
      lang: pt