site_name: 'asdasd'
docs_dir: '../../docs/en'                           # Where to find the English markdown files
site_dir: '../../build/en'                      # Where to put the English HTML files

theme:
  name: material
  language: en
extra:
  alternate:
    - name: English
      link: https://jodyphelan.github.io/test-docs/en/
      lang: en
    - name: Português
      link: https://jodyphelan.github.io/test-docs/pt/
      lang: pt